spring:
  application:
    name: sharedbudget
  liquibase:
    change-log: classpath:liquibase/changelog-master.xml
    enabled: true

  jpa:
    generate-ddl: false
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
        jdbc:
          lob.non_contextual_creation: true

  datasource:
    url: jdbc:postgresql://localhost:5432/sharedbudget
    username: SHAREDBUDGET
    password: SHAREDBUDGET
